const types = {
    //Global state
    SET_OR_REMOVE_LOADING: 'SET_OR_REMOVE_LOADING',
    IS_ACCESS: 'IS_ACCESS',
    SET_ERROR_MESSAGES: 'SET_ERROR_MESSAGES',

    //
    GET_FOODS: 'GET_FOODS',
    SET_FOODS: 'SET_FOODS',

    //
    GET_USER: 'GET_USER',
    GET_USER_BY_ID: 'GET_USER_BY_ID',
    SET_USER_BY_ID: 'SET_USER_BY_ID',

    //login page actions
    TOGGLE_LOGIN_PAGE: 'TOGGLE_LOGIN_PAGE',

    //login
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',

    //Auth
    IS_LOGIN: 'IS_LOGIN',
    SET_SIGNIN_USER_DATA: 'SET_SIGNIN_USER_DATA',
    OUT_USER_PAGE: 'OUT_USER_PAGE',
    REGISTRETED_USER:'REGISTRETED_USER'
};

export default types;
